### ISSUE TITLE
ceph-helm for single node deployment

### ISSUE THREAD

**Issue by costrouc** [ceph/ceph-helm#36]
**Is this a request for help?**: yes

I am looking to use the ceph-helm chart to deploy on a single node kubernetes cluster.  I have followed [this tutorial](https://palmerville.github.io/2016/04/30/single-node-ceph-install.html) and successfully got ceph running without kubernetes on a single node. Now I want to get it running within kubernetes using `ceph-helm`.

To clarify my understanding. I can basically follow the tutorial on the [ceph documentation for kubernetes + helm](http://docs.ceph.com/docs/master/start/kube-helm/). The only differences are:

1. the single node must be labeled with both 
    - **ceph-monitor:** ceph-mon=enabled ceph-mgr=enabled
    - **ceph-osd:** ceph-osd=enabled ceph-osd-device-dev-sdb=enabled ceph-osd-device-dev-sdc=enabled ...
2. I must set `osd pool default size = 2` and `osd crush chooseleaf type = 0` in `ceph-overrides.yaml`

How would I complete step 2? Please correct me it step 1 is not correct.

**Comment by intlabs** [comment]
this should provide some pointers I hope:
 * https://github.com/portdirect/sydney-workshop/blob/master/02-ceph.sh
 * https://github.com/openstack/openstack-helm/blob/master/tools/overrides/mvp/ceph.yaml

**Comment by costrouc** [comment]
I will not be able to test this until tomorrow. From quickly looking at the links ( especially 'mvp/ceph.yaml' )
it looks like it solves my problem. Thank you @intlabs!

**Comment by alram** [comment]
Closing as it appears to have fixed the issue. @costrouc feel free to re-open if needed.
