### ISSUE TITLE
Deploying ceph multiple times causes authentication error.

### ISSUE THREAD

**Issue by saitejar** [ceph/ceph-helm#43]
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
kubernetes 1.8.3

**Which chart**:
ceph

**What happened**:
I have a kubernetes deployment running. When I try to deploy ceph for the first time, it works fine. 
But when I purge ceph helm chart and redeploy ceph, ceph-mon, ceph-mon-check works fine but ceph-mds, ceph-mgr have an authentication failure and timeout connecting to ceph-mon.

**What you expected to happen**:
I would expect that all the services are able to connect to monitor without any authentication issues.

**How to reproduce it** (as minimally and precisely as possible):
Deploy ceph, purge ceph chart, deploy ceph again.

**Anything else we need to know**:
Something to note: I am not deleting the hostpath folder in the nodes on which ceph is being re deployed. I was expecting that redeploying would persist the content of ceph.

**Comment by alram** [comment]
You need to delete `/var/lib/ceph-helm/ceph/mon/*` manually on each ceph-mon host before a re-run. 
We haven't been able to work on fixing this yet

**Comment by saitejar** [comment]
@alram Would that persist the data ?

**Comment by alram** [comment]
No if you redeploy there's no persistence, you'll lose your data.
