### ISSUE TITLE
Integration of Ceph Exporter

### ISSUE THREAD

**Issue by betermieux** [ceph/ceph-helm#44]
Hi,
I was looking for a metrics exporter for prometheus and found a general exporter at: [ceph/ceph-container/examples/helm/ceph](https://github.com/ceph/ceph-container/tree/master/examples/helm/ceph/templates/exporter)

Would it be possible to integrate the exporter into this project? I am not very good at writing helm charts, and the structure of both charts seems to differ a lot.

Thanks,
Stefan

**Comment by rootfs** [comment]
cc @dmick

**Comment by dmick** [comment]
The strategy for Ceph and Prometheus is an exporter built as a manager module.  Enabling the module and advertising the address/port should be done by the manager deployment.  I'm not certain if that's yet done, but that's where to look.

**Comment by dmick** [comment]
By manager I mean ceph-mgr

**Comment by betermieux** [comment]
Yes, the manager module prometheus looks appropriate. It is working out of the box by adding the following snippet to `ceph-overrides.yaml`:
```
ceph_mgr_enabled_modules:
  - restful
  - status
  - prometheus
```
There seems to be no chance to add metadata/annotations to the deployment of the manager. I helped myself by patching the deployment afterwards.

**Comment by dmick** [comment]
Easy enough to add Values for annotations
