### ISSUE TITLE
How can I adjust the number of pgs ?

### ISSUE THREAD

**Issue by saitejar** [ceph/ceph-helm#46]
I have a running ceph deployment in kubernetes. What is the suggested way to adjust the number of pgs dynamically(as more osds(nodes) get added) with the ceph-helm deployment?

**Comment by alram** [comment]
There's no k8s job to handle that. Just like with baremetal, you'd run `ceph osd pool set <pool> <pg_num|pgp_num> <value>` from one of the ceph-mon container

**Comment by saitejar** [comment]
got it. thank you. @alram
