### ISSUE TITLE
Behavior when removing an OSD node

### ISSUE THREAD

**Issue by alram** [ceph/ceph-helm#5]
When removing a OSD node from the cluster:
`$ kubectl label node mira115 ceph-osd=disabled --overwrite`

The ceph-osd PODs are deleted however the OSD are marked down and are still present in the cluster.
The expected behavior since it's a node removal should include running the following commands:
 - for each OSD: `ceph osd purge <osd>`
 - Then: `ceph osd crush rm <hostname>`
 - maybe: zap the OSD drives?

Otherwise, adding back this node, we end up with:
```
-2       12.59991     host mira115
 1   hdd  0.89999         osd.1      down        0 1.00000
 2   hdd  0.89999         osd.2      down        0 1.00000
 3   hdd  0.89999         osd.3      down        0 1.00000
 5   hdd  0.89999         osd.5      down        0 1.00000
 6   hdd  0.89999         osd.6      down        0 1.00000
17   hdd  0.89999         osd.17     down        0 1.00000
18   hdd  0.89999         osd.18     down  1.00000 1.00000
20   hdd  0.89999         osd.20       up  1.00000 1.00000
21   hdd  0.89999         osd.21       up  1.00000 1.00000
22   hdd  0.89999         osd.22       up  1.00000 1.00000
23   hdd  0.89999         osd.23       up  1.00000 1.00000
24   hdd  0.89999         osd.24       up  1.00000 1.00000
25   hdd  0.89999         osd.25       up  1.00000 1.00000
26   hdd  0.89999         osd.26       up  1.00000 1.00000
```

**Comment by rootfs** [comment]
another thought is to have a `remove_osd.sh` just like [remove_mon.sh](https://github.com/ceph/ceph-helm/blob/master/ceph/ceph/templates/daemonset-mon.yaml#L88)

**Comment by alram** [comment]
Sounds good. 
I just tried to run a `kubectl drain mira115` to see if remove_mon.sh is executed -we definitely don't wan't that for OSDs- the local storage is detected and the PODs are not terminated
